Repository cdktf/construct-projen-template, pull requests merged in 2025-01, with the labels that each got.

#87 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#88 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node.yml
  .projenrc.ts
Labels: auto-approve, automerge

#89 chore(ci): add workflow for upgrading jsii & typescript
  .gitattributes
  .github/workflows/upgrade-jsii-typescript.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/upgrade-jsii-typescript.ts
  yarn.lock
Labels: auto-approve, automerge

#91 chore(ci): fix jsii & typescript upgrade workflow
  .github/workflows/upgrade-jsii-typescript.yml
  projenrc/upgrade-jsii-typescript.ts
  scripts/update-jsii-typescript.sh
Labels: auto-approve, automerge

#90 chore: upgrade jsii & typescript to v5.5
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve, automerge, automated

#92 docs: create maintenance guide
  .github/MAINTENANCE.md
Labels: auto-approve, automerge

#93 chore(ci): update required version of constructs when cdktf is upgraded
  .github/MAINTENANCE.md
  .github/workflows/upgrade-cdktf.yml
  .projenrc.ts
  projenrc/upgrade-cdktf.ts
  scripts/update-cdktf.sh
Labels: auto-approve, automerge

#94 chore(ci): pin version of cssstyle to allow upgrade-main to succeed
  .github/workflows/upgrade-node.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  projenrc/upgrade-node.ts
  yarn.lock
Labels: auto-approve, automerge

#97 chore(ci): automate jsii & typescript updates
  .github/MAINTENANCE.md
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/upgrade-jsii-typescript.ts
  scripts/check-jsii-versions.js
Labels: auto-approve, automerge

#101 chore(ci): bring workflows in line with standards
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  projenrc/auto-approve.ts
  projenrc/automerge.ts
Labels: auto-approve, automerge

#100 chore(ci): improve workflow based on learnings from upgrade-node
  .github/workflows/upgrade-jsii-typescript.yml
  projenrc/upgrade-jsii-typescript.ts
Labels: auto-approve, automerge

#98 chore(ci): make upgrade-node workflow manually triggerable
  .github/MAINTENANCE.md
  .github/workflows/upgrade-node.yml
  projenrc/upgrade-node.ts
  scripts/check-node-versions.js
Labels: auto-approve, automerge

#102 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies

#103 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies
